#### Чернышова Дана, группа 6209
##### Вариант 21
##### Лабораторная работа №2.2

In [3]:
import numpy as np
np.set_printoptions(precision=3, suppress=True) # set precision

Задание 1. Создать квадратную матрицу из случайных целых чисел из [-7,-1] размера 6 . Найти ее определитель, используя LU разложение.

In [7]:
n = 6 # set dimensions
A = np.random.randint(-7,0,(n,n)) 
U =  np.random.uniform(0, 0, (n,n)) 
L =  np.random.uniform(0, 0, (n,n))
for i in range(n): # Заполнение матриц L и U
    for j in range(n):
        if i <= j:
            U[i, j] = A[i, j] - np.dot(L[i, :i], U[:i, j]) #Находим матрицу U
        else:
            L[i, j] = (A[i, j] - np.dot(L[i, :j], U[:j, j])) / U[j, j] #Находим матрицу L
            
print('A =\n', A, '\n')
print('L*U =\n', np.dot(L, U), '\n')
print('L =\n', L, '\n')
print('U =\n', U)

detA = 1
for i in range(0,n):
    detA *= U[i][i]

print('\nLU determinant: ', detA.round(3))
print('\nlinalg determionant: ', np.linalg.det(A).round(3))

A =
 [[-6 -2 -2 -3 -6 -5]
 [-1 -7 -7 -1 -4 -2]
 [-4 -2 -3 -5 -2 -3]
 [-3 -4 -7 -6 -7 -1]
 [-5 -6 -1 -4 -7 -2]
 [-5 -3 -2 -2 -1 -5]] 

L*U =
 [[  0.      0.      0.      0.      0.      0.   ]
 [ -1.     -0.333  -0.333  -0.5    -1.     -0.833]
 [ -4.     -2.     -2.     -2.05   -4.3    -3.45 ]
 [ -3.     -4.     -7.    -10.575   2.55   -1.675]
 [ -5.     -6.     -1.     -4.     14.792  -9.525]
 [ -5.     -3.     -2.     -2.     -1.     -5.885]] 

L =
 [[ 0.     0.     0.     0.     0.     0.   ]
 [ 0.167  0.     0.     0.     0.     0.   ]
 [ 0.667  0.1    0.     0.     0.     0.   ]
 [ 0.5    0.45   3.     0.     0.     0.   ]
 [ 0.833  0.65  -5.    -3.481  0.     0.   ]
 [ 0.833  0.2   -1.    -0.514 -0.092  0.   ]] 

U =
 [[ -6.     -2.     -2.     -3.     -6.     -5.   ]
 [  0.     -6.667  -6.667  -0.5    -3.     -1.167]
 [  0.      0.     -1.     -2.95    2.3     0.45 ]
 [  0.      0.      0.      4.575  -9.55    0.675]
 [  0.      0.      0.      0.    -21.792   7.525]
 [  0.      

Задание 2. Найдите QR разложение матрицы, созданной в пункте 1. Проверьте правильность найденного разложения 1) с помощью умножения Q на R 2) с помощью функции np.linalg.qr

In [ ]:
Q =  np.random.uniform(0, 0, (n,n))

Q[:,0] = A[:,0]
for i in range(0,n):
    Q[:,i] = A[:,i]
    for j in range(0,i):
        Q[:,i]-=Q[:,j]*((A[:,i]*Q[:,j]).sum())/((Q[:,j]*Q[:,j]).sum())

for j in range(0,n):
    num = 0
    for i in range(0,n):
        num += Q[i,j]**2
    num = num**0.5
    Q[:,j]/=num
    

Q_1 = Q.transpose()
R = Q_1.dot(A)
q, r = np.linalg.qr(A) #проверяем с помощью функции np.linalg.qr

print('A =\n', A)
print('Q*R = \n', q.dot(r))
print('Q =\n', np.around(Q, decimals=2, out=None))
print('R =\n', np.around(R, decimals=2, out=None))


Задание 3. Решить систему, используя метод простых итераций с точностью до 10^-3, приведя к виду, удобному для итераций
$\left\{\begin{matrix}
3.2x_{1}-2.5x_{2}+3.7x_{3} = 6.5 & & \\
0.5x_{1}+0.34x_{2}+1.7x_{3} = -0.24 & & \\
1.6x_{1}+2.3x_{2}-1.5x_{3} = 4.3 & &
\end{matrix}\right.$

In [38]:
A = np.matrix([[3.2, -2.5, 3.7, 6.5], [0.5, 0.34, 1.7, -0.24], [1.6, 2.3, -1.5, 4.3]])

A[1,:]+=A[2,:]
A[0,:]+=2*A[2,:]
A[2,:]-=A[1,:]
# print("\nМатрица, пригодная для метода простых итераций:\n",a)
#6.4>2.1+0.7
#2.64>2.1+0.2
#|-1.7|>|-0.5|+|-0.34|

A = np.matrix([[0, -2.1, -0.7, 15.1], [-2.1, 0, -0.2, 4.06], [0.5, 0.34, 0, 0.24]])

A[0, :] /= 6.4
A[1, :] /= 2.64
A[2, :] /= -1.7
print(f"\nNew A matrix\n {A}")

x_i = np.random.uniform(0, 0, (3, 1))
x_i1 = np.random.uniform(0, 0, (3, 1))
print(f"\nVector 0: {x_i.T}")

e = 0.001 # set accurace

n = 1
maximum = 1
while maximum > e: # while needed accuracy hasn't been reached
    x_i1 = x_i.copy()    
    
    for i in range(0, 3):
        x_i[i] = A[i, 3] # fill the vector
        for j in range(0, 3): 
            x_i[i] += x_i1[j] * A[i, j] #Xn=Xn-1*Aij
            
    for k in range(0, 3): # find max|Xn+1 - Xn| to make sure |Xn+1 - Xn|<e
        x_i1[k] = abs((x_i[k] - x_i1[k]))
    maximum = np.max(x_i1)
    
    
    print(f"Vector {n}: {x_i.T}")
    print(f"Delta: {maximum}\n")
    
    n+=1
    
print(np.linalg.solve([[3.2, -2.5, 3.7], [0.5, 0.34, 1.7], [1.6, 2.3, -1.5]], [6.5, -0.24, 4.3]))


New A matrix
 [[ 0.    -0.328 -0.109  2.359]
 [-0.795  0.    -0.076  1.538]
 [-0.294 -0.2   -0.    -0.141]]

Vector 0: [[0. 0. 0.]]
Vector 1: [[ 2.359  1.538 -0.141]]
Delta: 2.359375

Vector 2: [[ 1.87  -0.328 -1.143]]
Delta: 1.8660803810160427

Vector 3: [[ 2.592  0.137 -0.626]]
Delta: 0.7218477354542665

Vector 4: [[ 2.383 -0.477 -0.931]]
Delta: 0.6133706353745622

Vector 5: [[ 2.618 -0.287 -0.747]]
Delta: 0.23465507127476837

Vector 6: [[ 2.535 -0.488 -0.854]]
Delta: 0.2006107247094739

Vector 7: [[ 2.613 -0.414 -0.789]]
Delta: 0.07751899517936645

Vector 8: [[ 2.582 -0.481 -0.827]]
Delta: 0.0665366040370835

Vector 9: [[ 2.608 -0.453 -0.804]]
Delta: 0.027644538027698562

Vector 10: [[ 2.596 -0.475 -0.817]]
Delta: 0.02233348339294977

Vector 11: [[ 2.605 -0.465 -0.81 ]]
Delta: 0.010167851744457834

Vector 12: [[ 2.601 -0.473 -0.814]]
Delta: 0.007569208469693667

Vector 13: [[ 2.604 -0.469 -0.811]]
Delta: 0.0036869441821107962

Vector 14: [[ 2.602 -0.472 -0.813]]
Delta: 0.0025850728