#### Чернышова Дана, группа 6209
##### Вариант 21
##### Лабораторная работа №2

In [57]:
import numpy as np
np.set_printoptions(precision=2)

Задание 1. Создать квадратную матрицу из случайных целых чисел из [-3, 3] размера 10. Найти и вычислить минор 4 порядка, расположенный на пересечениии 2, 3, 4, 5 строк и 7, 8, 9, 10 столбцов. Использовать срезы матрицы.

In [85]:
A = np.random.randint(-3,4,(10, 10))
print(np.linalg.det(A[1:5, 6:10]))

-78.0


Задание 2. Создать 2 матрицы из случайных вещественных чисел из интервала (2, 3) подходящего размера. Найти их произведение тремя способами: (1) использовать векторный алгоритм умножения матриц (2) используя матричный алгоритм, записав матрицу С по столбцам (3) проверив с помощью функции np.dot.

In [86]:
n = 3
k = 4
m = 5

A =  np.random.uniform(2, 3, (n, k))
B = np.random.uniform(2, 3, (k, m))

In [87]:
# (1) vector multiplication
C = np.zeros((n, m), dtype = float)

for i in range(n):
    for j in range(m):
        C[i,j] = np.dot(A[i, :], B[:, j])

print(C)

[[25.88 24.04 26.95 25.07 24.13]
 [25.7  24.37 26.64 25.26 24.5 ]
 [26.19 24.74 27.37 26.25 25.19]]


In [88]:
# (2) matrix multiplication
C = np.zeros((n, m), dtype = float)

for i in range(n):
    C[i,:] = np.dot(A[i,:], B)

print(C)

[[25.88 24.04 26.95 25.07 24.13]
 [25.7  24.37 26.64 25.26 24.5 ]
 [26.19 24.74 27.37 26.25 25.19]]


In [89]:
#  (3) check with np.dot

print('A * B =\n', np.dot(A, B))

A * B =
 [[25.88 24.04 26.95 25.07 24.13]
 [25.7  24.37 26.64 25.26 24.5 ]
 [26.19 24.74 27.37 26.25 25.19]]


Задание 3. Создать произвольную верхнетреугольную матрицу А пятого порядка (не унитреугольную), вектор В произвольный. Решить систему АХ = В.

In [90]:
A = np.triu(np.random.randint(1, 11, (4, 4)))
B = np.random.uniform(0, 11, 4) # vector

print('\nupper triangular matrix:\n', A, '\n\nvector:\n', B)
print('\nautomatic solution:\n', np.linalg.solve(A, B))

B[-1] = B[-1] / A[-1, -1]
for i in range(len(B) - 2, -1, -1):
	B[i] = (B[i] - np.dot(A[i, i + 1:], B[i + 1:])) / A[i, i]

print('\nfunction result:\n', B)


upper triangular matrix:
 [[ 6  9  3  2]
 [ 0  9  4  6]
 [ 0  0  2  5]
 [ 0  0  0 10]] 

vector:
 [ 2.64  3.46 10.87  5.13]

automatic solution:
 [ 0.9  -1.8   4.16  0.51]

function result:
 [ 0.9  -1.8   4.16  0.51]


Задание 4. Решить систему, используя LU разложение
$$ 
4.4x_1 - 2.5x_2 + 19.2x_3 - 10.8x_4 = 4.3\\
5.5x_1 - 9.3x_2 - 14.2x_3 + 13.2x_4 = 6.8\\
7.1x_1 - 11.5x_2 + 5.3x_3 - 6.7x_4 = -1.8\\
14.2x_1 + 23.4x_2 - 8.8x_3 + 5.3x_4 = 7.2
$$

In [91]:
n = 4
A = np.array([[4.4, -2.5, 19.2, -10.8],
              [5.5, -9.3, -14.2, 13.2],
              [7.1, -11.5, 5.3, -6.7],
              [14.2, 23.4, -8.8, 5.3]])
B = np.array([[4.3], [6.8], [-1.8], [7.2]])
U = np.zeros((n, n), float)
L = np.identity(n, float)

for i in range(n):
    for j in range(n):
        if i <= j:
            U[i, j] = A[i, j] - np.dot(L[i, :i], U[:i, j])
        else:
            L[i, j] = (A[i, j] - np.dot(L[i, :j], U[:j, j])) / U[j, j]

print('\nL matrix:\n', L)
print('\nU martix:\n', U)
print('\nLU matrix:\n', np.dot(L, U))
print('\ninitial matrix\n', A)


L matrix:
 [[  1.     0.     0.     0.  ]
 [  1.25   1.     0.     0.  ]
 [  1.61   1.21   1.     0.  ]
 [  3.23  -5.1  -12.95   1.  ]]

U martix:
 [[   4.4    -2.5    19.2   -10.8 ]
 [   0.     -6.18  -38.2    26.7 ]
 [   0.      0.     20.5   -21.55]
 [   0.      0.      0.   -102.81]]

LU matrix:
 [[  4.4  -2.5  19.2 -10.8]
 [  5.5  -9.3 -14.2  13.2]
 [  7.1 -11.5   5.3  -6.7]
 [ 14.2  23.4  -8.8   5.3]]

initial matrix
 [[  4.4  -2.5  19.2 -10.8]
 [  5.5  -9.3 -14.2  13.2]
 [  7.1 -11.5   5.3  -6.7]
 [ 14.2  23.4  -8.8   5.3]]
