#### Чернышова Дана, группа 6209
##### Вариант 21
##### Лабораторная работа №3

In [6]:
import numpy as np

Задание 1. Создать вектор строку 1x10 из случайных целых чисел. Вычислить норму ||x||1 самостоятельно написанной функцией и проверить результат с помощью linalg.norm()

In [11]:
A = np.random.randint(0, 10, (1, 10))[0] # generate a random vector

res = 0
for elem in A:
    res += abs(elem) # sum absolute values of each element

print(res) # calculated manually
print(np.linalg.norm(A, ord=1)) # check

50
50.0


Задание 2. Создать матрицу из случайных целых чисел. Найти спектральную норму матрицы с помощью самостоятельно написанного алгоритма (можно использовать функцию для нахождения собственных значений), проверить результат с помощью linalg.norm().

In [48]:
n = 3 # set dimensions
A = np.random.randint(0, 10, (n, n))

AtA = np.cross(A.transpose(), A) # multiply transposed A and the regular one
u, s, vh = np.linalg.svd(A) # get singular values from singular value decomposition
print(max(s)) # print the max of singular values

np.linalg.norm(A, ord=2) # check

14.590203221067116


14.590203221067112

Задание 3. Для вектора, созданного в первом пункте, найти отражение Хаусхолдера, которое обнуляет его координаты с 4 по 10. Например, вектор (1,2,3,4,5,6,7,8,9,10) переводит в вектор
(1,2,3,0,0,0,0,0,0,0)

In [195]:
def find_qr(A):
    
    r = len(A)
    Q = np.eye(r)
    for i in range(3, 10): # borders are indexes to set to zero
        H = np.eye(r)
        H[i:, i:] = make_householder(A[i:])
        Q = np.dot(Q, H)
        A = np.dot(H, A)
    return Q, A
 
def make_householder(a):
    v = a / (a[0] + np.copysign(np.linalg.norm(a), a[0]))
    v[0] = 1
    H = np.eye(a.shape[0])
    H -= (2 / np.dot(v, v)) * np.dot(v[:, None], v[None, :])
    return H
 

A = np.random.randint(1, 10, (1, 10))[0]  # generate a random vector

q, r = find_qr(A)
print(A) # intial matrix
print('q:\n', q)
print('r:\n', r)




[5 3 2 8 7 4 5 2 3 5]
q:
 [[ 1.     0.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     1.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     1.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.    -0.577  0.744 -0.318 -0.015  0.1   -0.006 -0.046]
 [ 0.     0.     0.    -0.505 -0.019  0.854 -0.095 -0.062 -0.043  0.026]
 [ 0.     0.     0.    -0.289 -0.25  -0.077  0.904  0.022 -0.121 -0.125]
 [ 0.     0.     0.    -0.361 -0.474 -0.208 -0.298  0.711 -0.073 -0.051]
 [ 0.     0.     0.    -0.144 -0.125 -0.038  0.009 -0.085  0.943 -0.254]
 [ 0.     0.     0.    -0.217 -0.156 -0.16   0.028 -0.165  0.172  0.92 ]
 [ 0.     0.     0.    -0.361 -0.345 -0.306 -0.289 -0.668 -0.241 -0.262]]
r:
 [  5.      3.      2.    -13.856  -0.     -0.     -0.     -0.     -0.
   0.   ]


/var/folders/c0/f0v7p5v12k15tprf6q64l1tw0000gn/T/ipykernel_11089/884191726.py:13: RuntimeWarning: invalid value encountered in true_divide
  v = a / (a[0] + np.copysign(np.linalg.norm(a), a[0]))


Задание 4. Решить систему, используя QR разложение, полученное
преобразованием Хаусхолдера.
$$ 
4.4x_1 - 2.5x_2 + 19.2x_3 - 10.8x_4= 4.3\\
5.5x_1 - 9.3x_2 - 14.2x_3 + 13.2x_4= 6.8\\
7.1x_1 - 11.5x_2 + 5.3x_3 - 6.7x_4= -1.8\\
14.2x_1 + 23.4x_2 - 8.8x_3 + 5.3x_4= 7.2
$$

In [152]:
def householder(A):

    (r, c) = np.shape(A)
    Q = np.identity(r)
    R = np.copy(A)

    for cnt in range(r-1):
        x = R[cnt:, cnt]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        u = x-e
        v = u /np.linalg.norm(u)
        Q_cnt = np.identity(r)
        Q_cnt[cnt:, cnt:] -= 2.0 * np.outer(v, v)
        R = np.dot(Q_cnt, R)
        Q = np.dot(Q, Q_cnt)
    
    return Q, R


In [154]:
A = np.array([[4.4, -2.5, 19.2, -10.8], [5.5, -9.3, -14.2, 13.2], [7.1, -11.5, 5.3, -6.7], [14.2, 23.4, -8.8, 5.3]])
B = np.array([4.3, 6.8, -1.8, 7.2])

np.set_printoptions(precision=3, suppress=True) # set precision

Q, R = householder(A)
y = np.dot(Q.T, B)
x = np.linalg.solve(R, y) # solve Rx = Q`b

print(x) # solved manually
print(np.linalg.solve(A, B)) # automatic check

[0.445 0.067 0.869 1.312]
[0.445 0.067 0.869 1.312]
